./elastic-mapreduce --create --name "conta palavra mais usada com 15 instancias" \
--stream --mapper  'ruby s3n://trab2cloud/map/map_conta_palavras_diferentes.rb' \
     --input   s3n://trab2cloud/input/* \
     --output  s3n://trab2cloud/out/palavra+usada/temp2 \
     --reducer 'ruby s3n://trab2cloud/reduce/reduce_conta_palavra+_usada.rb' \
     --num-instances 15 \
--stream --mapper  /bin/cat \
     --input   s3n://trab2cloud/out/palavra+usada/temp2/* \
     --output  s3n://trab2cloud/out/palavra+usada/15instancias \
     --reducer 'ruby s3n://trab2cloud/reduce/reduce_conta_palavra+_usada.rb' \
     --args -D,mapred.reduce.tasks=1 \
